image:
  file: .gitpod.Dockerfile
ports:
    - port: 8000
      onOpen: ignore
      visibility: public
    - port: 5432
      onOpen: ignore
      visibility: private
tasks:
  - init: >
      (cp -n .env.example .env || true) && 
    command: >
        poetry config virtualenvs.in-project true &&
        poetry shell &&
        source .venv/bin/activate &&
        poetry install &&
        uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: false

vscode:
  extensions:
    - ms-python.python