image:
  file: .gitpod.Dockerfile
ports:
    - port: 8000
      onOpen: ignore
      visibility: public
    - port: 5432
      onOpen: ignore
      visibility: private
    - port: 5050
      onOpen: ignore
      visibility: public
    - port: 9999
      onOpen: ignore
      visibility: public
tasks:
  - name: lesson
    init: |
      echo $LESSON && cd $LESSON
      docker-compose pull
      poetry config virtualenvs.in-project true
      poetry shell 
      source .venv/bin/activate 
      poetry install 
    command: |
      docker-compose up -d
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: false

vscode:
  extensions:
    - ms-python.python